name: PR Preview

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  deploy-preview:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./

  remove-preview:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: rossjrw/pr-preview-action@v1
        with:
          action: remove
